### ISSUE TITLE
Integrate with Poetry

### ISSUE THREAD

**Issue by gabrielecalvo** [UltiRequiem/chuy#1]
It would be nice if instead of defining a separate JSON file one could write the commands in the project.toml. perhaps under a section [tool.chuy]

PS: Very nice project! I've been looking for something like this! =)

**Comment by UltiRequiem** [comment]
I am already working on this in: https://github.com/UltiRequiem/poetry-chuy-plugin

**Comment by gabrielecalvo** [comment]
Nice! Thanks for the quick response. Sorry I must have missed the notification.
I was thinking more of directly loading the pyproject.toml in chuy without needing poetry.
So to be able to say `chuy..` instead of `poetry chuy ..`

**Comment by UltiRequiem** [comment]
Now working :)

https://github.com/UltiRequiem/chuy/commit/720998735ef100eb8751387ba2277d74afb5dc69
