### ISSUE TITLE
chuy with multiple commands doesn't stop if one errors out

### ISSUE THREAD

**Issue by gabrielecalvo** [UltiRequiem/chuy#8]
As per title, non erroring might create issues as users might rely on commands are run only after previous commands succeed.

For example
`chuy create-container test`
The test probably will rely on the container bring created.

Suggestion (to be tested):
https://github.com/UltiRequiem/chuy/blob/7d15303d3431b79e79f8339939323efc7de2f3d5/chuy/helpers.py#L91
We might want to consider changing it to:
`subprocess.run(command, shell=True, check=True)`

**Comment by gabrielecalvo** [comment]
@UltiRequiem happy to close this given https://github.com/UltiRequiem/chuy/commit/8cb55efb2953c9975682660db05d0025876965a8?

**Comment by UltiRequiem** [comment]
Yep, thanks @gabrielecalvo!
